//Apis
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

//Auth
export const BEGIN_LOADING_USER = 'BEGIN_LOADING_USER';
export const LOADING_USER_COMPLETE = 'LOADING_USER_COMPLETE';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const ADD_SOCKET = 'ADD_SOCKET';

//Modals
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

//Lists
export const REORDER_LIST = 'REORDER_LIST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS';
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';

//Tasks
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const TOGGLE_TASK_SUCCESS = 'TOGGLE_TASK_SUCCESS';
export const CLEAR_TASKS_SUCCESS = 'CLEAR_TASKS_SUCCESS';
export const UPDATE_ACTIVE_TASK_ORDER = 'UPDATE_ACTIVE_TASK_ORDER';
export const UPDATE_COMPLETED_TASK_ORDER = 'UPDATE_COMPLETED_TASK_ORDER';

//Visibility
export const UPDATE_VISIBILITY = 'UPDATE_VISIBILITY';
