export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS';
export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
